const apostleCreed=`我信上帝，全能的父，創造天地的主宰。我信耶穌基督，上帝的獨生子，咱的主。祂由聖神投胎，由在室女馬利亞出世；佇本丟彼拉多任內受苦，\n\n釘十字架，死，埋葬，落陰府；第三日由死人中復活，升天，今坐佇全能的父上帝的大傍；祂要自彼再來審判活人及死人。\n\n我信聖神，聖閣公同的教會，聖徒的相通，罪的赦免；肉體的復活；永遠的活命。阿們。`;
const lordPrayer=`阮在天裡的父。願祢的名聖；祢的國臨到，祢的旨意得成，在地裡親像在天裡。\n\n阮的日食，今仔日給阮。赦免阮的辜負，親像阮亦有赦免辜負阮的人。\n\n勿得導阮入於試，著救阮脫離彼個惡的。因為國、權能、榮光攏是祢所有，代代無盡。阿們。`;
const creedPptPages=[
  {title:'信仰告白—使徒信經',body:`我信上帝，全能的父，創造天地的主宰。我信耶穌基督，上帝的獨生子，咱的主。祂由聖神投胎，由在室女馬利亞出世；佇本丟彼拉多任內受苦，`,align:'left',showTitle:true},
  {title:'信仰告白—使徒信經',body:`釘十字架，死，埋葬，落陰府；\n第三日由死人中復活，升天，\n今坐佇全能的父上帝的大傍；\n祂要自彼再來審判活人及死人。`,align:'left',showTitle:true},
  {title:'信仰告白—使徒信經',body:`我信聖神，聖閣公同的教會，\n聖徒的相通，罪的赦免；肉體的復活；\n永遠的活命。阿們。`,align:'left',showTitle:true}
];
const lordPrayerPptPages=[
  {title:'主禱文',body:`阮在天裡的父。願祢的名聖；\n祢的國臨到，祢的旨意得成，\n在地裡親像在天裡。`,align:'center',showTitle:true},
  {title:'主禱文',body:`阮的日食，今仔日給阮。\n赦免阮的辜負，\n親像阮亦有赦免辜負阮的人。`,align:'center',showTitle:true},
  {title:'主禱文',body:`勿得導阮入於試，著救阮脫離彼個惡的。\n因為國、權能、榮光攏是祢所有，\n代代無盡。阿們。`,align:'center',showTitle:true}
];
const sections=[
  ['cover','台語主日禮拜','cover'],['prelude-singing','會前領唱','title'],['silence','靜默一分鐘','title'],['prelude','序樂','title'],['call','宣召','calendar'],['hymn-1','聖詩一','hymn'],['creed','信仰告白—使徒信經','fixed'],['response','啟應文','port'],['prayer-1','祈禱','title'],['lord-prayer','主禱文','fixed'],['prayer-song','祈禱詩','fixed-title'],['scripture','聖經','calendar'],['praise','讚美','praise'],['sermon','講道','sermon'],['prayer-2','祈禱','title'],['hymn-2','聖詩二','hymn'],['announcements','報告','manual'],['verse','金句','calendar'],['offering','奉獻','fixed-title'],['doxology','頌榮','calendar'],['blessing','祝禱','title'],['amen','阿們頌','fixed-title'],['postlude','後奏','title'],['peace','平安禮','title']
];
const model=Object.fromEntries(sections.map(([id,label,type])=>[id,{label,type,title:label,kicker:'',body:'',opacity:60}]));
model.creed.body=apostleCreed;model.creed.pptPages=creedPptPages;model['lord-prayer'].body=lordPrayer;model['lord-prayer'].pptPages=lordPrayerPptPages;let active='prelude-singing';let backgroundColor='#ffffff';try{const draft=JSON.parse(localStorage.getItem('lkc-taiwanese-worship-draft')||'{}');backgroundColor=window.TaiwaneseWorshipSlideProduction?.normalizeColor(draft.backgroundColor,'#ffffff')||'#ffffff'}catch(error){console.warn('背景色草稿讀取失敗',error)}const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function field(label,key,value='',type='text',hint=''){return `<label class="field"><span>${label}</span>${type==='textarea'?`<textarea data-key="${key}">${esc(value)}</textarea>`:`<input data-key="${key}" value="${esc(value)}">`}${hint?`<small>${hint}</small>`:''}</label>`}
function flow(){ $('#flow-list').innerHTML=sections.map(([id,label],i)=>`<button class="flow-item ${id===active?'active':''}" data-id="${id}"><span class="flow-number">${String(i+1).padStart(2,'0')}</span>${label}</button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{active=b.dataset.id;render()})}
function editor(){const x=model[active],f=$('#editor-form');let html='';if(x.type==='fixed')html=`<div class="inline-note">內容依提供的台語禮拜 PPT 固定保留。</div>${field('內容','body',x.body,'textarea')}`;else if(x.type==='fixed-title')html=`<div class="inline-note">此段落在提供的 PPT 中為固定格式。歌詞或樂譜不在此頁自行產生。</div>`;else if(x.type==='port')html=`<div class="inline-note">保留啟應文資料庫端口。資料庫尚未串接前，請依本週資料手動貼入。</div>${field('標題','title',x.title)}${field('內容','body',x.body,'textarea')}`;else if(x.type==='hymn')html=`${field('聖詩編號與名稱','title',x.title,'text','聖詩資料庫端口保留。')}${field('樂譜／歌詞內容','body',x.body,'textarea')}<label class="field"><span>背景透明度</span><div class="range-wrap"><input id="opacity" type="range" min="40" max="80" value="${x.opacity}"><output class="range-value">${x.opacity}%</output></div></label>`;else if(x.type==='calendar')html=`<div class="inline-note">保留行事曆帶入端口；未串接前不預填任何文字。</div>${field('標題','title',x.title)}${field('內容','body',x.body,'textarea')}`;else if(x.type==='praise')html=`${field('詩歌名稱','title',x.title)}${field('演唱者／團體（選填）','kicker',x.kicker)}${field('歌詞（以空白行分頁）','body',x.body,'textarea','依你貼入的歌詞分頁，不自動生成歌詞。')}`;else if(x.type==='sermon')html=`${field('講道題目','title',x.title)}<div class="form-row">${field('講員','kicker',x.kicker)}${field('經文','body',x.body)}</div><label class="field"><span>牧師講道 PPT（選填）</span><input type="file" accept=".ppt,.pptx"></label>`;else if(x.type==='manual')html=`${field('標題','title',x.title)}${field('報告內容','body',x.body,'textarea','請直接貼入報告內容。')}`;else html=`${field('標題','title',x.title)}${field('副標題（選填）','kicker',x.kicker)}${field('內容（選填）','body',x.body,'textarea')}`;f.innerHTML=html;f.querySelectorAll('[data-key]').forEach(el=>el.oninput=e=>{x[e.target.dataset.key]=e.target.value;preview()});const opacity=$('#opacity');if(opacity)opacity.oninput=e=>{x.opacity=e.target.value;$('.range-value').textContent=e.target.value+'%';preview()}}
function preview(){const x=model[active];const pages=x.type==='praise'&&x.body?x.body.split(/\n\s*\n/).filter(Boolean).length:1;const setText=(selector,value)=>{const element=$(selector);if(element)element.textContent=value};setText('#preview-name',x.label);setText('#preview-kicker',x.kicker);setText('#preview-title',x.title);setText('#preview-body',x.body);setText('#slide-count',`${pages} 頁`);const bg=$('.slide-background');if(bg){bg.style.backgroundImage='none';bg.style.backgroundColor=backgroundColor;bg.style.opacity=x.type==='hymn'?(100-Number(x.opacity))/100:1}}
function render(){flow();editor();preview();$('#section-kind').textContent=model[active].type==='fixed'||model[active].type==='fixed-title'?'固定內容':model[active].type==='calendar'?'行事曆帶入端口':'流程內容';$('#section-title').textContent=model[active].label}function status(t){$('#save-state').textContent=t}
const backgroundInput=$('#background-color');backgroundInput.value=backgroundColor;backgroundInput.oninput=e=>{backgroundColor=window.TaiwaneseWorshipSlideProduction.normalizeColor(e.target.value,'#ffffff');preview();status(`已套用純色背景：${backgroundColor}`)};
$('#save-draft').onclick=()=>{localStorage.setItem('lkc-taiwanese-worship-draft',JSON.stringify({model,backgroundColor}));status('已儲存至此瀏覽器')};$('#calendar-load').onclick=()=>status('行事曆端口已保留，等待資料欄位映射後帶入');$('#export-ppt').onclick=()=>status('PPTX 匯出端口已保留，將依提供的 PPT 格式實作');const localIsoDate=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('#service-date').value=localIsoDate();$('#service-date').addEventListener('input',()=>{if(active==='cover')preview()});$('#service-date').addEventListener('change',()=>{if(active==='cover')preview()});render();
